-- English strings for Transmute Set Crafter

ZO_CreateStringId("SI_TSC_TITLE",                  "Transmute Set Crafter")
ZO_CreateStringId("SI_TSC_INVENTORY_HEADER",        "Item Sets")
ZO_CreateStringId("SI_TSC_BACK_PREFIX",             "← ")
ZO_CreateStringId("SI_TSC_SET_PIECE_COUNT",         "<<1>> pieces")
ZO_CreateStringId("SI_TSC_QUEUE_HEADER",            "Queue")
ZO_CreateStringId("SI_TSC_TARGET_TRAIT_LABEL",      "Target Trait:")
ZO_CreateStringId("SI_TSC_SELECT_TRAIT_PROMPT",     "-- select trait --")
ZO_CreateStringId("SI_TSC_ENCHANTMENT_LABEL",       "Enchantment:")
ZO_CreateStringId("SI_TSC_ENCHANTMENT_PLACEHOLDER", "e.g. Weapon Damage")
ZO_CreateStringId("SI_TSC_QUALITY_LABEL",           "Quality:")
ZO_CreateStringId("SI_TSC_SELECT_QUALITY_PROMPT",   "-- select quality --")
ZO_CreateStringId("SI_TSC_ADD_TO_QUEUE",            "Add to Queue")
ZO_CreateStringId("SI_TSC_ADD_COUNT_TO_QUEUE",      "Add to Queue (<<1>>)")
ZO_CreateStringId("SI_TSC_TRANSMUTE_ALL",           "Reconstruct All (<<1>>)")
ZO_CreateStringId("SI_TSC_CLEAR_QUEUE",             "Clear Queue")
ZO_CreateStringId("SI_TSC_CRYSTALS_COST",           "Crystals needed: <<1>>  /  Available: <<2>>")
ZO_CreateStringId("SI_TSC_QUEUE_ROW_DETAIL",        "<<1>>  ·  <<2>>")
ZO_CreateStringId("SI_TSC_EMPTY_QUEUE",             "Queue is empty")
ZO_CreateStringId("SI_TSC_NOT_AT_STATION",          "Must be at a Transmutation Station (Reconstruct tab)")
ZO_CreateStringId("SI_TSC_INSUFFICIENT_CRYSTALS",   "Not enough Transmute Crystals (need <<1>>, have <<2>>)")
ZO_CreateStringId("SI_TSC_ITEM_NOT_FOUND",          "Item Set piece no longer available: <<1>>")
ZO_CreateStringId("SI_TSC_TRANSMUTE_FAILED",        "Reconstruction failed: <<1>>")
ZO_CreateStringId("SI_TSC_FILTER_WEAPONS",          "Weapons")
ZO_CreateStringId("SI_TSC_FILTER_ARMOR",            "Armor")
ZO_CreateStringId("SI_TSC_FILTER_JEWELRY",          "Jewelry")
ZO_CreateStringId("SI_TSC_TRAIT_NOT_RESEARCHED",    " (not researched)")
ZO_CreateStringId("SI_TSC_SEARCH_PLACEHOLDER",      "Search by set name...")
ZO_CreateStringId("SI_BINDING_NAME_TSC_TOGGLE",     "Toggle Transmute Set Crafter")

-- Settings
ZO_CreateStringId("SI_TSC_SETTINGS_PANEL_NAME",     "Transmute Set Crafter")
ZO_CreateStringId("SI_TSC_SETTINGS_CLOSE_ON_EXIT",  "Close on station exit")
ZO_CreateStringId("SI_TSC_SETTINGS_CLOSE_ON_EXIT_TOOLTIP", "Automatically close the window when you leave a Transmutation Station.")
ZO_CreateStringId("SI_TSC_SETTINGS_AUTO_OPEN",      "Open at station")
ZO_CreateStringId("SI_TSC_SETTINGS_AUTO_OPEN_TOOLTIP", "Automatically open the window when you interact with a Transmutation Station.")
